#!/bin/bash
# Azure SQL Firewall Configuration Script for Railway IP
# Adds Railway's current IP address to Azure SQL Server firewall rules

echo "🔥 Azure SQL Firewall Configuration for iQube Railway Deployment"
echo "=================================================================="

# Railway IP from logs
RAILWAY_IP="208.77.244.18"
AZURE_SQL_SERVER="iqube-sql-jaswant"
RULE_NAME="Railway-Production-IP"

echo "📊 Current Configuration:"
echo "  Azure SQL Server: ${AZURE_SQL_SERVER}.database.windows.net"
echo "  Railway IP Address: ${RAILWAY_IP}"
echo "  Firewall Rule Name: ${RULE_NAME}"
echo ""

echo "🔧 Azure CLI Commands to Run:"
echo "================================"
echo ""

echo "1. Login to Azure CLI:"
echo "   az login"
echo ""

echo "2. Set your subscription (if needed):"
echo "   az account set --subscription \"your-subscription-id\""
echo ""

echo "3. Add Railway IP to firewall rules:"
echo "   az sql server firewall-rule create \\"
echo "     --resource-group \"your-resource-group\" \\"
echo "     --server \"${AZURE_SQL_SERVER}\" \\"
echo "     --name \"${RULE_NAME}\" \\"
echo "     --start-ip-address \"${RAILWAY_IP}\" \\"
echo "     --end-ip-address \"${RAILWAY_IP}\""
echo ""

echo "4. Verify the firewall rule was added:"
echo "   az sql server firewall-rule list \\"
echo "     --resource-group \"your-resource-group\" \\"
echo "     --server \"${AZURE_SQL_SERVER}\""
echo ""

echo "🌐 Alternative: Azure Portal Method"
echo "===================================="
echo ""
echo "1. Go to: https://portal.azure.com"
echo "2. Navigate to: SQL servers → ${AZURE_SQL_SERVER}"
echo "3. Click: Networking (in the left sidebar)"
echo "4. Under 'Firewall rules', click: Add a firewall rule"
echo "5. Enter:"
echo "   - Rule name: ${RULE_NAME}"
echo "   - Start IP: ${RAILWAY_IP}"
echo "   - End IP: ${RAILWAY_IP}"
echo "6. Click: Save"
echo ""

echo "⚡ Quick Test Commands"
echo "======================"
echo ""
echo "Test Railway health endpoint:"
echo "curl https://genrate-with-ai-feature-production.up.railway.app/health"
echo ""
echo "Test database status endpoint (after firewall fix):"
echo "curl https://genrate-with-ai-feature-production.up.railway.app/api/status/database"
echo ""
echo "Test authentication endpoint (after firewall fix):"
echo "curl -X POST https://genrate-with-ai-feature-production.up.railway.app/api/auth/login \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"email\":\"test@example.com\",\"password\":\"testpass\"}'"
echo ""

echo "🎯 Expected Results After Firewall Fix:"
echo "========================================"
echo "✅ Database status endpoint returns 'connected' status"
echo "✅ Authentication endpoints return proper error messages (not 500)"
echo "✅ User registration and login work correctly"
echo "✅ No more 'Client with IP address not allowed' errors in Railway logs"
echo ""

echo "📝 Notes:"
echo "========="
echo "- Railway IP addresses can change during deployments"
echo "- Monitor Railway logs for new IP addresses if issues recur"
echo "- Consider adding a range of Railway IPs if available"
echo "- The firewall change takes effect immediately"
echo ""

echo "🚨 If Railway IP Changes:"
echo "========================="
echo "1. Check Railway deployment logs for new IP"
echo "2. Update firewall rule with new IP address"
echo "3. Or add additional firewall rules for multiple IPs"
echo ""

echo "✅ Run this script completed!"
echo "Now execute the Azure CLI commands above to fix the firewall."
