# Nixpacks configuration (DISABLED - using Dockerfile instead)
# Uncomment this file only if Dockerfile deployment fails
# and you need to fall back to Nixpacks

# [phases.setup]
# nixPkgs = ["nodejs-18_x"]

# [phases.install]
# cmds = [
#   "cd backend",
#   "npm install --omit=dev",
#   "npm cache clean --force"
# ]

# [phases.build]
# cmds = [
#   "cd backend",
#   "npm prune --omit=dev",
#   "echo 'Build complete - dependencies optimized'"
# ]

# [start]
# cmd = "cd backend && npm run railway:start"

# [variables]
# NODE_ENV = "production"
# PORT = "3001"
