[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install --omit=dev",
  "npm cache clean --force"
]

[phases.build]
cmds = [
  "npm prune --omit=dev",
  "echo 'Build complete - dependencies optimized'"
]

[start]
cmd = "npm run railway:start"

[variables]
NODE_ENV = "production"
PORT = "3001"
