[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "cd backend",
  "npm install"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
