[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd backend",
  "npm ci --only=production",
  "npm run verify"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
