# Nixpacks configuration for full-stack deployment
# React frontend + Express backend with optimized build process

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm ci --omit=dev --prefer-offline",
  "npm install --only=dev",
  "npm cache clean --force"
]

[phases.build]
cmds = [
  "npm run railway:build",
  "echo '🔍 Checking if images were copied:'",
  "ls -la dist/ || echo 'No dist directory'",
  "ls -la dist/lovable-uploads/ || echo 'No dist/lovable-uploads directory'",
  "ls -la public/lovable-uploads/ || echo 'No public/lovable-uploads directory'",
  "npm prune --omit=dev",
  "npm cache clean --force",
  "echo '✅ Full-stack build complete - React frontend built and dependencies optimized'"
]

[start]
cmd = "npm run railway:start"

[variables]
NODE_ENV = "production"
RAILWAY_DEPLOYMENT = "true"
