# Nixpacks configuration for full-stack deployment
# React frontend + Express backend with optimized build process

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm ci --omit=dev --prefer-offline",
  "npm install --only=dev",
  "npm cache clean --force"
]

[phases.build]
cmds = [
  "npm run railway:build",
  "npm prune --omit=dev",
  "npm cache clean --force",
  "echo 'Full-stack build complete - React frontend built and dependencies optimized'"
]

[start]
cmd = "npm run railway:start"

[variables]
NODE_ENV = "production"
RAILWAY_DEPLOYMENT = "true"
