# Railway configuration for monorepo structure
# FORCE Docker usage - disable Nixpacks completely

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/health"
interval = 10
timeout = 5
threshold = 3

[environments.production]
variables = { NODE_ENV = "production" }
