# Railway configuration for backend deployment
# Backend files are now in root directory

[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "npm run railway:start"

[healthcheck]
path = "/health"
interval = 10
timeout = 5
threshold = 3

[environments.production]
variables = { NODE_ENV = "production" }
