[build]
builder = "nixpacks"
workingDirectory = "backend"
buildCommand = "npm install --omit=dev"

[deploy]
startCommand = "node --experimental-specifier-resolution=node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/health"
interval = 10
timeout = 5
threshold = 3

[environments.production]
variables = { NODE_ENV = "production" }
