# Railway configuration for monorepo structure
# Works with both Docker and Nixpacks

[build]
builder = "nixpacks"
watchPatterns = ["backend/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "cd backend && npm install --omit=dev && npm run railway:start"

[healthcheck]
path = "/health"
interval = 10
timeout = 5
threshold = 3

[environments.production]
variables = { NODE_ENV = "production" }
