# Railway configuration for full-stack deployment
# React frontend + Express backend in single deployment

[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/health"
interval = 10
timeout = 5
threshold = 3

[environments.production]
variables = {
  NODE_ENV = "production",
  RAILWAY_DEPLOYMENT = "true",
  PORT = "8080"
}
