[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci --only=production"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[environments.production]
variables = { NODE_ENV = "production" }
